### PR TITLE
Escaped unicode for sylabus_txt

### PR DESCRIPTION
**Pull request by SirRichardVanEsquire**
I added this patch on my own xbmc to fix an error parsing unicode characters in the syllabus text of the course 'Introduction to Classical Music'.

My git skills are limited and this is my first pull request, so please forgive me if I've done it wrong. If so, feel free to just review the change and add it (or something similar) to your own code.

### CODE REVIEW

**Comment by asfaltboy** [comment]
Here is the exception when trying to view the above course:

    22:14:47 T:4413984768   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
       - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
      Error Type: <type 'exceptions.UnicodeEncodeError'>
      Error Contents: 'ascii' codec can't encode character u'\xf6' in position 48: ordinal not in range(128)
      Traceback (most recent call last):
        File ".../Kodi/addons/plugin.video.coursera/addon.py", line 291, in <module>
          plugin.run()
        File ".../Kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
          items = self._dispatch(self.request.path)
        File ".../Kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
          listitems = view_func(**items)
        File ".../Kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 81, in wrapper
          result = function(*args, **kwargs)
        File ".../Kodi/addons/plugin.video.coursera/addon.py", line 102, in listCourses
          courseShortName=get_session_short_name(sessions[0]))
        File ".../Kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 81, in wrapper
          result = function(*args, **kwargs)
        File ".../Kodi/addons/plugin.video.coursera/addon.py", line 132, in listCourseContents
          sylabus = getSylabus(courseShortName, username, password)
        File ".../Kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 81, in wrapper
          result = function(*args, **kwargs)
        File ".../Kodi/addons/plugin.video.coursera/course_utils.py", line 108, in getSylabus
          parsed = parse_syllabus(sylabus_txt)
        File ".../Kodi/addons/plugin.video.coursera/course_utils.py", line 303, in parse_syllabus
          data_lecture_view_link)
        File ".../lib/python2.6/logging/__init__.py", line 1036, in debug
        File ".../lib/python2.6/logging/__init__.py", line 1165, in _log
        File ".../lib/python2.6/logging/__init__.py", line 1174, in handle
        File ".../lib/python2.6/logging/__init__.py", line 570, in filter
        File ".../Kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/logger.py", line 70, in filter
          xbmc.log('%s%s' % (self.prefix, record.getMessage()), xbmc_level)
      UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 48: ordinal not in range(128)
      -->End of Python script error report<--

**Comment by asfaltboy** [comment]
Hi @SirRichardVanEsquire, I think removing all non-ascii characters is a bit harsh. Have a look in your fork, I added a pull request to your fix branch which might resolve the issue without doing this.

**Comment by cancan101** [comment]
Is this still relevant?

**Comment by asfaltboy** [comment]
Oh yeah definitely, with this courses with content that contains special characters can be supported.

**Pull request merged**
